eureka:
  instance:
    hostname : hello-test.internal
    instanceId:  hello-test.internal
#    instanceId:  hello-test.internal:9091
    preferIpAddress: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://192.168.49.2/eureka/

spring:
  datasource:
    url: jdbc:mysql://192.168.49.2:3306/restaurantdb
    password: hbstudent
    username: hbstudent
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect