eureka:
  instance:
#    hostname : hello-test.internal
#    instanceId:  hello-test.internal
##    instanceId:  hello-test.internal:9091
#    preferIpAddress: true
    preferIpAddress: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
#      defaultZone: http://192.168.49.2/eureka/
      defaultZone: http://172.17.0.1:8761/eureka/

spring:
  datasource:
#    url: jdbc:mysql://192.168.49.2:3306/restaurantdb
    url: jdbc:mysql://172.17.0.1:3306/restaurantdb
    password: password
    username: sammy
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect